# Generated by Django 4.1.3 on 2022-11-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='date_and_time_of_publication',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
