# Generated by Django 4.1.3 on 2022-11-29 12:51

import BookLoversApp.accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, validators=[BookLoversApp.accounts.validators.validate_only_letters])),
                ('cover_photo', models.URLField()),
                ('author', models.CharField(max_length=70, validators=[BookLoversApp.accounts.validators.validate_only_letters])),
                ('pages', models.PositiveIntegerField()),
                ('year_of_first_publication', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
