# Generated by Django 4.1.3 on 2022-11-29 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beloved_characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='belovedcharacter',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='books.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='belovedcharacter',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
