# Generated by Django 4.1.3 on 2022-12-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_comment_photo_comment_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
